#ABNF 1.0 GB2312;

/*
 * Copyright 2013 allan.
 * All Rights Reserved.
 * 
 * 连续剧查询
 * 
 * 包含了语法和语义的用法
 * 
 */

language zh-CN;
mode voice;

root $main;

$main = $MyTvSeriseList;

//查询我有在追哪些剧目，在追什么连续剧（美剧）
//默认前三个字段是查询所有连续剧种类，也就是返回 MyTvSeriseList_All
$MyTvSeriseList = { out = "MyTvSeriseList_All"; } 我的节目[单] | 我的追剧 | 我[在][追]的连续剧 | 我在追的剧[目] 
					 | $myUS_TV | $myUK_TV | $myJP_TV;

$myUS_TV = (绝命毒师 | (Breaking Bad)!en-us) { out.text = "绝命毒师"; }
	| (汉尼拔 | (Hannibal)!en-us) { out.text = "汉尼拔"; }
	| (豪斯医生 | (House)!en-us) { out.text = "豪斯医生"; }
	| (行尸走肉 | (The Walking Dead)!en-us) { out.text = "行尸走肉"; }
	| 国土安全 
	| 童话镇 
	| 吸血鬼日记 
	| 生活大爆炸 
	| 疑犯追踪 
	| 绿箭 
	| 格林 
	| 始祖家族 
	| 福尔摩斯 演绎法 
	| 惊魂序曲 
	| 反击 
	| 嗜血法医 
	| 权力的游戏 
	| 新闻编辑室 
	| 昭雪 
	| 发展受阻 
	| 英雄 
	| 24小时 
	| 迷失 
	| 犯罪心理 
	| 失落的房间 迷之屋 
	| 八卦天后 
	| 别对我撒谎 
	| 傲骨贤妻 
	| 猫鼠游戏 
	| 尼基塔 
	| 斯巴达克斯 
	| 太平洋战争 
	| 惊世 
	| 绝对界限 
	| 南国医恋 
	| 打工姐妹花 
	| 记忆神探 
	| 陨落星辰 
	| 诉讼双雄 
	| 少狼 
	| 谋杀 
	| 替身姐妹 
	| 秘社 
	| 九命美少女 
	| 永恒岛 
	| 真爱如血 
	| 恶魔岛 
	| 破釜沉舟 
	| 触摸未来 
	| 神盾局特工 
	| 广告狂人 
	| 人质 
	| 杀手信徒 
	| 断头谷 
	| 冬日斜阳 
	| 清道夫 
	| 达芬奇的恶魔 
	| 零点时刻 
	| 纸牌屋 
	| 杀无赦 
	| 铁杉树丛;

$myUK_TV = 猎杀行动 | 新福尔摩斯;

$myJP_TV = LEGAL HIGH | 半泽直树;